- name: "setup DNS"
  lineinfile: dest=/etc/resolv.conf line="nameserver 192.168.0.254" create=yes

- name: "installing webserver"
  package: name=nginx state=present

- name: "start nginx"
  service: name=nginx state=started enabled=yes 

