#!/bin/bash

action=$(basename $0)

stop_vm_if_needed() {
  local status=$(VBoxManage showvminfo "${vbox_image}" --machinereadable | grep -w VMState | cut -d'=' -f2)

  if [ ${status} == \"running\" ];
  then
    VBoxManage controlvm "${vbox_image}" poweroff
   fi
}

stop_all() {

  for vbox_image in webserver1 webserver2
  do
    stop_vm_if_needed ${vbox_image}
  done
}

case $action in
    start)
        VBoxManage startvm --type headless "webserver1"
        VBoxManage startvm --type headless "webserver2"
        ;;
    stop)
        stop_all
        ;;
    reset)
        stop_all
        VBoxManage snapshot "webserver1" restorecurrent
        VBoxManage snapshot "webserver2" restorecurrent
        ;;
esac


