# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "C.UTF-8" # https://oncletom.io/2015/docker-encoding/

Vagrant.configure("2") do |config|

  (1..2).each do |i|
    config.vm.define "webserver#{i}" do |node|
    
      node.vm.box = "debian/jessie64"
      node.vm.hostname = "webserver#{i}"
      node.vm.network "private_network", ip: "192.168.50.10#{i}"
#      node.vm.provision :shell do |s|
#         s.inline = <<-EOT
#           echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
#         EOT
#       end
    end
  end


end
